#!/bin/sh

DAEMON="relayd"                                         
PIDFILE="/var/run/$DAEMON.pid"

start() {
	printf "Starting $DAEMON: "
	/sbin/start-stop-daemon --start -q --background --exec /usr/sbin/$DAEMON --make-pidfile -p $PIDFILE
        [ $? = 0 ] && echo "OK" || echo "FAIL"
}

stop() {
        printf "Stopping $DAEMON: "
	/sbin/start-stop-daemon -q --stop -p $PIDFILE
        [ $? = 0 ] && echo "OK" || echo "FAIL"
}

case "$1" in 
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		stop
		start
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
esac

exit 0 
